name = "cloud-notepad"
main = "src/index.js"
compatibility_date = "2022-05-13"

kv_namespaces = [
  { binding = "NOTES", id = "d41d9962287541e597d5f39ca14fed20" },
  { binding = "SHARE", id = "0a1678d85f4f463791f973cb3fa70f8a" }
]